CREATE TABLE TCOMMENTS (
  ID MEDIUMINT AUTO_INCREMENT,
  POST_ID MEDIUMINT NOT NULL,
  COMMENT_NAME VARCHAR(500),
  COMMENT_BODY VARCHAR(1000),
  CONSTRAINT PK_TCOMMENT PRIMARY KEY(ID),
  CONSTRAINT FK_TCOMMENT FOREIGN KEY(POST_ID) REFERENCES TPOSTS(ID)
);
