server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  #sql:
  #  init:
  #    schema-locations: classpath:ddl/DDL_DROP.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPRODUCTS.sql, classpath:ddl/DDL_TPRODUCT_DISCOUNTS.sql, classpath:ddl/DDL_TSHOPPING_CARTS.sql, classpath:ddl/DDL_TINVOICES.sql
      # data-locations: classpath:DML_STUDENTS.sql
  #    mode: always # always
spring.jpa:
  # properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  #properties:
  #   hibernate.hbm2ddl.auto: none
  hibernate.ddl-auto: none  # for exercise/ testing use only
  #spring.jpa.properties.hibernate.hbm2ddl.auto=create
  show-sql: true

api:
  jsonplaceholder: 
    domain: 'jsonplaceholder.typicode.com'
    user:
      endpoint: '/users'
    post:
      endpoint: '/posts'
    comment:
      endpoint: '/comments'




      #==========redis 配置信息===========#

#（单机redis）数据库ip
spring.data.redis:
  host: 127.0.0.1
#（单机redis）数据库端口
  port: 6379
  database: 0
  password: 
  timeout: 5000
  jedis.pool:
    max-active: 1999
    max-idle: 10
    min-idle: 2
    max-wait: -1

