
-- DROP TABLE TUSERS;
-- DROP TABLE TPRODUCTS;
-- DROP TABLE TPRODUCT_DISCOUNTS;
-- DROP TABLE TSHOPPING_CARTS;
-- DROP TABLE TINVOICES;

DROP TABLE IF EXISTS TINVOICES;
DROP TABLE IF EXISTS TSHOPPING_CARTS;
DROP TABLE IF EXISTS TUSERS;
DROP TABLE IF EXISTS TPRODUCT_DISCOUNTS;
DROP TABLE IF EXISTS TPRODUCTS;

