CREATE TABLE TPRODUCT_DISCOUNTS (
  ID MEDIUMINT AUTO_INCREMENT,
  PRODUCT_ID MEDIUMINT NOT NULL,
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME,
  UNIT_DISCOUNT_RATIO NUMERIC(5,2),
  UNIT_DISCOUNT_PRICE NUMERIC(10,2),
  STATUS VARCHAR(1) NOT NULL,
  CONSTRAINT PK_TPRODUCT_DISCOUNT PRIMARY KEY(ID),
  CONSTRAINT FK_TPRODUCT_DISCOUNT FOREIGN KEY(PRODUCT_ID) REFERENCES TPRODUCTS(ID)
);