DROP TABLE IF EXISTS TINVOICES;
DROP TABLE IF EXISTS TSHOPPING_CARTS;
DROP TABLE IF EXISTS TPRODUCT_DISCOUNTS;
DROP TABLE IF EXISTS TPRODUCTS;
DROP TABLE IF EXISTS TUSERS;

CREATE TABLE TUSERS (
  USER_ID VARCHAR(10),
  USER_NAME VARCHAR(20),
  USER_EMAIL VARCHAR(50),
  CONSTRAINT PK_TUSER PRIMARY KEY(USER_ID)
);