-- DROP TABLE CHANNEL_COIN_MAPPINGS;
CREATE TABLE IF NOT EXISTS CHANNEL_COIN_MAPPINGS (
    ID INTEGER auto_increment PRIMARY KEY,
    CHANNEL_ID INTEGER NOT NULL,
    COIN_CODE VARCHAR(10) NOT NULL, 
    COIN_ID VARCHAR(50) NOT NULL, 
    LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT current_timestamp,
    CONSTRAINT UC_COIN_MAPPING UNIQUE (CHANNEL_ID, COIN_CODE),
    CONSTRAINT FK_CHANNEL_COIMN_MAPPING FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)
);