server:
  port: 8080

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html

# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
