CREATE table IF NOT EXISTS TUSERS (
  ID serial,
  NAME VARCHAR(100),
  USER_NAME VARCHAR(100),
  USER_EMAIL VARCHAR(50),
  USER_PHONE VARCHAR(50),
  USER_WEBSITE VARCHAR(100),
  CONSTRAINT PK_TUSER PRIMARY KEY(ID)
);